workflows:
  ios-simulator-v2:
    name: Kivy iOS Simulator Build
    instance_type: mac_mini_m2
    max_build_duration: 60

    environment:
      vars:
        XCODE_WORKSPACE: PowerRideApp.xcworkspace
        XCODE_SCHEME: PowerRideApp

    scripts:
      - name: Install toolchain & dependencies
        script: |
          brew update
          brew install autoconf automake libtool pkg-config
          pip install "Cython<3"
          pip install kivy-ios

      - name: Build Python + Kivy
        script: |
          toolchain build python3 kivy

      - name: Create Xcode project
        script: |
          toolchain create PowerRideApp .

      - name: Build for iOS Simulator (unsigned)
        script: |
          cd PowerRideApp-ios
          xcodebuild -project PowerRideApp.xcodeproj \
                     -scheme PowerRideApp \
                     -sdk iphonesimulator \
                     -configuration Debug \
                     ONLY_ACTIVE_ARCH=NO \
                     build

    artifacts:
      - PowerRideApp-ios/build/Debug-iphonesimulator/PowerRideApp.app
