workflows:
  kivy-ios-sim-v2:
    name: Kivy iOS Simulator Build
    instance_type: mac_mini_m2
    max_build_duration: 60

    environment:
      vars:
        XCODE_WORKSPACE: PowerRideApp.xcodeproj  # Matches Kivy-generated project
        XCODE_SCHEME: PowerRideApp                # Matches Kivy-generated scheme

scripts:
  - name: Install toolchain & dependencies
    script: |
      brew update
      brew install autoconf automake libtool pkg-config sdl2 sdl2_image sdl2_mixer sdl2_ttf freetype zlib  # Explicit deps for common failures
      pip install "Cython==0.29.36"  # Pin to stable Kivy-iOS version (avoids 3.x bugs)
      pip install kivy-ios

  - name: Build Python + Kivy
    script: |
      toolchain build python3 kivy  # Retry logic: if fails, try with --ignore-cache
      # If above fails, uncomment: toolchain clean && toolchain build python3 kivy

  - name: Create Xcode project
    script: |
      toolchain create PowerRideApp .

  - name: Build for iOS Simulator (unsigned)
    script: |
      cd PowerRideApp-ios
      xcodebuild -project PowerRideApp.xcodeproj \
                 -scheme PowerRideApp \
                 -sdk iphonesimulator \
                 -configuration Debug \
                 ONLY_ACTIVE_ARCH=NO \
                 build

    artifacts:
      - PowerRideApp-ios/build/Debug-iphonesimulator/PowerRideApp.app
