workflows:
  kivy-ios-device-build:
    name: Kivy iOS Device Build
    instance_type: mac_mini_m2
    max_build_duration: 60

    environment:
      vars:
        XCODE_WORKSPACE: PowerRideApp.xcodeproj
        XCODE_SCHEME: PowerRideApp
        APP_STORE_PROFILE_NAME: $APP_STORE_PROFILE_NAME
        APP_STORE_CONNECT_TEAM_ID: $APP_STORE_CONNECT_TEAM_ID
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.throttleordie.throttle-or-die-app

    scripts:
      - name: Install toolchain & dependencies
        script: |
          brew update
          brew install autoconf automake libtool pkg-config sdl2 sdl2_image sdl2_mixer sdl2_ttf freetype zlib
          pip install "Cython==0.29.36"
          pip install kivy-ios

      - name: Build Python + Kivy
        script: |
          toolchain build python3 kivy

      - name: Create Xcode project
        script: |
          toolchain create PowerRideApp .

      - name: Build and archive for device
        script: |
          cd PowerRideApp-ios
          xcodebuild clean archive \
            -archivePath "$(pwd)/../build/PowerRideApp.xcarchive" \
            -project "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -configuration Release \
            -sdk iphoneos \
            CODE_SIGN_STYLE=Manual \
            CODE_SIGN_IDENTITY="iPhone Distribution" \
            PROVISIONING_PROFILE_SPECIFIER="$APP_STORE_PROFILE_NAME" \
            DEVELOPMENT_TEAM="$APP_STORE_CONNECT_TEAM_ID" \
            -destination 'generic/platform=iOS'

      - name: Export IPA
        script: |
          xcodebuild -exportArchive \
            -archivePath "$(pwd)/../build/PowerRideApp.xcarchive" \
            -exportOptionsPlist export_options.plist \
            -exportPath "$(pwd)/../build"

    artifacts:
      - build/**/*.ipa
